<a href="https://colab.research.google.com/github/RadJeff7/zerotopandas-course/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1I0p1ASukYEKbgJdHjCqI5oYQOYhNhScS')

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Some Interesting Numpy Functions


### Here, we will take a look at five interesting numpy functions!

Numpy is a python package for scientific computing that provides high-performance multidimensional arrays objects. This library is widely used for numerical analysis, matrix computations, and mathematical operations.

### - numpy.full_like
### - numpy.stack
### - numpy.linspace
### - numpy.reshape
### - numpy.matmul

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations-radjeff')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "radjeff7/numpy-array-operations-radjeff" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/radjeff7/numpy-array-operations-radjeff


'https://jovian.ml/radjeff7/numpy-array-operations-radjeff'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
# List of functions explained 
''' function1 = np.full_like 
function2 = ???
function3 = ???
function4 = ???
function5 = ??? '''

' function1 = np.full_like \nfunction2 = ???\nfunction3 = ???\nfunction4 = ???\nfunction5 = ??? '

## Function 1 - numpy.full_like 


            numpy.full_like(a, fill_value, dtype=None)

Here, the function will return a full array with the same shape and type as a given array.

#### Parameters


a : This is the given array variable name.
    The shape and data-type of a define these same attributes of the returned array.

fill_value : The output array will be filled with this particular value.

dtype : The given data-type (optional) will override the data type of the result.


In [ ]:
# Example 1

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

out = np.full_like(a, 4)
print(out)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In the above example, the output array will be shaped like given array with all values as 4.

In [ ]:
# Example 2 - working
x = np.arange(6, dtype=int)
print(x)

out = np.full_like(x, 0.1, dtype=np.double)
print(out)

[0 1 2 3 4 5]
[0.1 0.1 0.1 0.1 0.1 0.1]


In the above example, the output array will be filled with a double value.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[[11, 14, 13], [1, 2, 5.5], 
        [3, 4., 6.25]]]

out = np.full_like(arr3, 'x', dtype= np.double)
print(out)

ValueError: could not convert string to float: 'x'

Here, the data type is not similar. so it raises a ValueError!

As it is a Numpy array creation routine, so it may be helpful to create a whole array with a singular value.


In [ ]:
jovian.commit()

## Function 2 - numpy.stack

            numpy.stack(arrays, axis=0, out=None)


The numpy.stack function joins a sequence of arrays along a new axis. In contrast with numpy.concatenate it creates a new axis along the existing one/s. With the stack function the input arrays must have the same shape.

### Parameters:

- arrays: sequence of arrays, Each array must have the same shape.

- axis: int value(optional). The axis parameter specifies the index of the new axis in the dimensions of the result. 
      
      if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.


- out: ndarray, optional.

     If provided, the destination to place the result. The shape must be correct, matching that of what stack would have              returned if no out argument were specified.


       The function returns stackedndarray
The stacked array has one more dimension than the input arrays.

In [ ]:
# Example 1 - working
arr1 = np.array([[3, 4], 
                [5, 6.]])

arr2 = np.array([[9, 6], 
                [7, 8]])

out = np.stack((arr1, arr2), axis=1)
print(arr1)
print(arr2)
print(out)

[[3. 4.]
 [5. 6.]]
[[9 6]
 [7 8]]
[[[3. 4.]
  [9. 6.]]

 [[5. 6.]
  [7. 8.]]]


Explanation about example

In [ ]:
# Example 2 - working
arr3 = [[[1, 2, 3], [4, 5, 6], 
        [7, 8, 9]]]

arr4 = [[[10, 11, 12], 
        [13, 14, 15], 
        [16, 17, 18]]]

In [ ]:
out = np.stack((arr3, arr4), axis=0)
print(out)
print(out.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]]


 [[[10 11 12]
   [13 14 15]
   [16 17 18]]]]
(2, 1, 3, 3)


In [ ]:
out = np.stack((arr3, arr4), axis=1)
print(out)
print(out.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]]
(1, 2, 3, 3)


In [ ]:
out = np.stack((arr3, arr4), axis=-1)
print(out)
print(out.shape)

[[[[ 1 10]
   [ 2 11]
   [ 3 12]]

  [[ 4 13]
   [ 5 14]
   [ 6 15]]

  [[ 7 16]
   [ 8 17]
   [ 9 18]]]]
(1, 3, 3, 2)


In [ ]:
out = np.stack((arr3, arr4), axis=2)
print(out)
print(out.shape)

[[[[ 1  2  3]
   [10 11 12]]

  [[ 4  5  6]
   [13 14 15]]

  [[ 7  8  9]
   [16 17 18]]]]
(1, 3, 2, 3)


Notice how by changinng the axis value we change how the arrays are arranged.

We can confirm that an input of axis=-1 is somewhat equivalent to the transpose matrix operation, but only with the rows transformed into columns, resulting in three arrays with two columns each.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr5 = [[1, 2], 
        [4, 3]]

arr6 = [[5, 6, 7], 
        [8, 9, 10]]

np.stack((arr5, arr6), axis=0)

ValueError: all input arrays must have the same shape

The stack function will return an error if the input dimension of the first index (rows or lines) are different.

So, we need to give two arrays with the same shape for the np.stack to work properly!



We noticed that we stacked three arrays with 3 dimensions each. The final results were all 4 dimensional arrays. Hence the stack function may be useful in situations when we need to increase the dimension of our numerical dataset for some numerical operations, or when we want iterate over arrays of diferent dimensions, but want to have a final result with a higher dimension.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "radjeff7/numpy-array-operations-radjeff" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/radjeff7/numpy-array-operations-radjeff


'https://jovian.ml/radjeff7/numpy-array-operations-radjeff'

## Function 3 - numpy.linspace

        numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
       

This function returns evenly spaced numbers over a specified interval defined by the first two arguments of the function.


### Parameters:

- **start, stop** : required argument. Defines the starting value & end value of the sequence.

- **num** : Integer(optional). Defines number of samples to generate. Default is 50. 

- **endpoint** : Boolean(optional). If True, stop is the last sample. Otherwise, it is not included. Default is True.So, we have to keep in mind while working with this function is that the stop element is provided in the returned array (by default endpoint=True), unlike in the built-in python function range.

- **retstep** : Boolean(optional). If True, return (samples, step), where step is the spacing between samples.

- **dtype** : data_type(optional) The type of the output array. If dtype is not given, infer the data type from the other input              arguments.

- **axis** : Integer(optional). The axis in the result to store the samples. 


In [ ]:
# Example 1 - working
out = np.linspace(5, 7, num=5)
print(out)

out = np.linspace(5, 7, num=5, endpoint=False)
print(out)

out = np.linspace(5, 7, num=5, retstep=True)
print(out)

[5.  5.5 6.  6.5 7. ]
[5.  5.4 5.8 6.2 6.6]
(array([5. , 5.5, 6. , 6.5, 7. ]), 0.5)


Explanation about example

In [ ]:
# Example 2 - working

out = np.linspace([0,1.5],[1,-2],10,endpoint=False, axis=1)
print(out)
np.shape(out)

[[ 0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9 ]
 [ 1.5   1.15  0.8   0.45  0.1  -0.25 -0.6  -0.95 -1.3  -1.65]]


(2, 10)

The function can also generate multiple ranges. The function can also input negetive values for specitying the range.

Here, Two arrays with respective range (0,1) and (1.5, -2) are generated.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

out = np.linspace(5, 7, num=-5, endpoint=False)

ValueError: Number of samples, -5, must be non-negative.

The number of samples shuld not be negative.


So, we see that Linspace function can be used to generate evenly spaced samples for the x-axis. For instance, if we want to plot a mathematical function, we can easily generate samples for the x-axis by using the numpy.linspace function.


In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "radjeff7/numpy-array-operations-radjeff" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/radjeff7/numpy-array-operations-radjeff


'https://jovian.ml/radjeff7/numpy-array-operations-radjeff'

## Function 4 - numpy.reshape

        numpy.reshape(a, newshape, order='C')
        
The Numpy.reshape function gives us the ability to change the shape of an array without changing the content(data) of the array.

### Parameters: 

- **a** : array to be reshaped.
- **newshape** : Integer or Tuple of integers. The new shape should be compatible with the original shape. 
- **order** : It is a optional Parameter. These values are possible {‘C’, ‘F’, ‘A’}. This parameter directs to read the elements of a using this index order, and place the elements into the reshaped array using this index order.

In [ ]:
# Example 1 - working

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
after = np.reshape(before, (4,2))
print(after)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
after = np.reshape(before, 8)
print(after)

[1 2 3 4 5 6 7 8]


In [ ]:
after = np.reshape(before, (2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


We can now resahpe this array created with a changed ordering of the inputs indexes to the reshape function.
We can supply only 1 integer as newshape to create a 1D array or we can supply tuple of integers to get the desired shape.


In [ ]:
# Example 2 - working
b = np.arange(10).reshape((5, 2))
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
b = np.arange(10).reshape((5, 2), order='F')
print(b)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


Also, this function supports different types of orderings named as 'C' for ravel type shown above and 'F' for Fortran type shown below.

‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = np.reshape(before, (2,3))

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

Here, the error occurs because size incompatibility. The new shape should be compatible with the original shape.

The reshape function can be useful in many situations in numerical computing. For instance when we need to perform a matrix multiplication of two matrices (two dimensional arrays) but with one of the array not compatible with the specified order of multilication.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "radjeff7/numpy-array-operations-radjeff" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/radjeff7/numpy-array-operations-radjeff


'https://jovian.ml/radjeff7/numpy-array-operations-radjeff'

## Function 5 - numpy.matmul

The Numpy matmul() function is used to return the matrix product of 2 arrays. 
       
       numpy.matmul(x, y, out=None)

1) For 2-D arrays, it returns normal product.

2) For Dimensions > 2, the product is treated as a stack of matrix.

3) For 1-D array is first promoted to a matrix by appending a 1 to its dimension, which is removed after multiplication.


### Parameters : 

- x, y : Input arrays, scalars not allowed.

- out : ndarray, optional. A location into which the result is stored. If provided, it must have a shape that matches the signature 



In [ ]:
# Example 1 - working

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

here the column of first matrix and row of second matrix is of same value. So np.matmul() returns the Matrix multiplication result.

In [ ]:
# Example 2 - working

# one array having dimensions > 2 

a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
print(np.matmul(a,b))
print(np.matmul(a,b).shape)

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]
(2, 2, 2)


In the above example, one array having Dimensions > 2, So it is treated as a stack of matrices residing in the last two indexes and broadcasted accordingly.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.matmul([1,2], 3)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

Scalar multiplication raises an error.


numpy.matmul() is a very important linear algebra function. The Numpy matmul() function is used to return the matrix product of 2 arrays. 

In [ ]:
jovian.commit()

## Conclusion

Here, we have discussed about some of the important Numpy Functions with detailed examples.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html


In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>